### ISSUE TITLE
Bug in dependency - markupsafe 1.0

### ISSUE THREAD

**Issue by winston-young** [DormyMo/SpiderKeeper#118]
Python 3.6.9. 
Ubuntu 18.04.2

SpiderKeeper lists MarkupSafe 1.0 as a dependency. That version has a known issue related to setuptools. Updating SpiderKeeper to MarkupSafe >= 1.1 should fix it. 

https://github.com/pallets/markupsafe/issues/57#issuecomment-597105876

**Comment by uhlhosting** [comment]
I got the same: 


```
Collecting MarkupSafe==1.0
  Using cached MarkupSafe-1.0.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/qr/dppqcyyn2653gx33y3tb4qdc0000gn/T/pip-install-xy9kqrbq/markupsafe_34c40ff506e34765b1e0cacbaebb5c69/setup.py", line 6, in <module>
          from setuptools import setup, Extension, Feature
      ImportError: cannot import name 'Feature' from 'setuptools' (/usr/local/lib/python3.11/site-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

```
