### ISSUE TITLE
scrapyd的报错提示

### ISSUE THREAD

**Issue by seozed** [DormyMo/SpiderKeeper#16]
```
whoami@blackman:~/spider$ scrapyd
2017-04-19T09:59:46+0800 [-] Loading /home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/txapp.py...
2017-04-19T09:59:46+0800 [-] Scrapyd web console available at http://0.0.0.0:6800/
2017-04-19T09:59:46+0800 [-] Loaded.
2017-04-19T09:59:46+0800 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.1.0 (/home/whoami/.pyenv/versions/3.5.1/bin/python3.5 3.5.1) starting up.
2017-04-19T09:59:46+0800 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2017-04-19T09:59:46+0800 [-] Site starting on 6800
2017-04-19T09:59:46+0800 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site object at 0x7f29ee254f98>
2017-04-19T09:59:46+0800 [Launcher] Scrapyd 1.2.0a1 started: max_proc=8, runner='scrapyd.runner'
2017-04-19T09:59:48+0800 [_GenericHTTPChannelProtocol,0,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/Twisted-17.1.0-py3.5-linux-x86_64.egg/twisted/web/http.py", line 1906, in allContentReceived
            req.requestReceived(command, path, version)
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/Twisted-17.1.0-py3.5-linux-x86_64.egg/twisted/web/http.py", line 771, in requestReceived
            self.process()
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/Twisted-17.1.0-py3.5-linux-x86_64.egg/twisted/web/server.py", line 190, in process
            self.render(resrc)
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/Twisted-17.1.0-py3.5-linux-x86_64.egg/twisted/web/server.py", line 241, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/webservice.py", line 21, in render
            return JsonResource.render(self, txrequest).encode('utf-8')
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/utils.py", line 20, in render
            r = resource.Resource.render(self, txrequest)
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/Twisted-17.1.0-py3.5-linux-x86_64.egg/twisted/web/resource.py", line 250, in render
            return m(request)
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/webservice.py", line 112, in render_GET
            spiders = get_spider_list(project, runner=self.root.runner, version=version)
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/utils.py", line 137, in get_spider_list
            raise RuntimeError(msg.encode('unicode_escape') if six.PY2 else msg)
        builtins.RuntimeError: Scrapy 1.3.3 - no active project

        Unknown command: list

        Use "scrapy" to see available commands


2017-04-19T09:59:48+0800 [twisted.python.log#info] "127.0.0.1" - - [19/Apr/2017:01:59:47 +0000] "GET /listspiders.json?project=%E9%BB%98%E8%AE%A4 HTTP/1.1" 200 163 "-" "python-requests/2.13.0"
2017-04-19T09:59:49+0800 [_GenericHTTPChannelProtocol,1,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/Twisted-17.1.0-py3.5-linux-x86_64.egg/twisted/web/http.py", line 1906, in allContentReceived
            req.requestReceived(command, path, version)
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/Twisted-17.1.0-py3.5-linux-x86_64.egg/twisted/web/http.py", line 771, in requestReceived
            self.process()
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/Twisted-17.1.0-py3.5-linux-x86_64.egg/twisted/web/server.py", line 190, in process
            self.render(resrc)
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/Twisted-17.1.0-py3.5-linux-x86_64.egg/twisted/web/server.py", line 241, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/webservice.py", line 21, in render
            return JsonResource.render(self, txrequest).encode('utf-8')
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/utils.py", line 20, in render
            r = resource.Resource.render(self, txrequest)
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/Twisted-17.1.0-py3.5-linux-x86_64.egg/twisted/web/resource.py", line 250, in render
            return m(request)
          File "/home/whoami/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/webservice.py", line 123, in render_GET
            queue = self.root.poller.queues[project]
        builtins.KeyError: 'defaut'

2017-04-19T09:59:49+0800 [twisted.python.log#info] "127.0.0.1" - - [19/Apr/2017:01:59:48 +0000] "GET /listjobs.json?project=defaut HTTP/1.1" 200 68 "-" "python-requests/2.13.0"
^C2017-04-19T09:59:49+0800 [-] Received SIGINT, shutting down.
2017-04-19T09:59:49+0800 [-] (TCP Port 6800 Closed)
2017-04-19T09:59:49+0800 [twisted.web.server.Site#info] Stopping factory <twisted.web.server.Site object at 0x7f29ee254f98>
2017-04-19T09:59:49+0800 [-] Main loop terminated.
2017-04-19T09:59:49+0800 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
```

OS:ubuntu 16.04 64bit
看不懂这个报错，刚装好的scrapyd

**Comment by DormyMo** [comment]
project name 请用英文，如果在SpiderKeeper 中建的工程在scrapyd中不存在，请用SpiderKeeper的deploy来部署，如果是手动部署，请保持SpiderKeeper project name 与 scrapyd中的project name 一致

**Comment by seozed** [comment]
是用的deploy来部署的；
可是我还没上传egg文件呢，提示`builtins.KeyError: 'defaut'`

**Comment by seozed** [comment]
跟twisted有关系不，我是下载的源码包.tar.bz2安装的

**Comment by seozed** [comment]
```
2017-04-19T10:43:03+0800 [twisted.python.log#info] "192.168.1.100" - - [19/Apr/2017:02:43:02 +0000] "GET /listjobs.json?project=yuemei HTTP/1.1" 200 75 "-" "python-requests/2.13.0"
2017-04-19T10:43:15+0800 [_GenericHTTPChannelProtocol,49,192.168.1.100] Unhandled Error
        Traceback (most recent call last):
          File "/home/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/web/http.py", line 1906, in allContentReceived
            req.requestReceived(command, path, version)
          File "/home/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/web/http.py", line 771, in requestReceived
            self.process()
          File "/home/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/web/server.py", line 190, in process
            self.render(resrc)
          File "/home/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/web/server.py", line 241, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/home/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/webservice.py", line 21, in render
            return JsonResource.render(self, txrequest).encode('utf-8')
          File "/home/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/utils.py", line 20, in render
            r = resource.Resource.render(self, txrequest)
          File "/home/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
            return m(request)
          File "/home/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/webservice.py", line 123, in render_GET
            queue = self.root.poller.queues[project]
        builtins.KeyError: 'yingwen'

2017-04-19T10:43:15+0800 [twisted.python.log#info] "192.168.1.100" - - [19/Apr/2017:02:43:14 +0000] "GET /listjobs.json?
```

名字确实是英文的，但是不知道为什么报project name KeyError

**Comment by DormyMo** [comment]
按我上一条评论操作

**Comment by deperado123** [comment]
请问下这个问题解决了麽，我遇到了一模一样的问题：scrapyd中不存在工程，用SpiderKeeper的deploy来部署，仅是创建了工程，就报了 builtins.KeyError；
2018-08-23T15:38:25+0800 [_GenericHTTPChannelProtocol,3,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "e:\anaconda3\lib\site-packages\twisted\web\http.py", line 2059, in allContentReceived
            req.requestReceived(command, path, version)
          File "e:\anaconda3\lib\site-packages\twisted\web\http.py", line 869, in requestReceived
            self.process()
          File "e:\anaconda3\lib\site-packages\twisted\web\server.py", line 184, in process
            self.render(resrc)
          File "e:\anaconda3\lib\site-packages\twisted\web\server.py", line 235, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "e:\anaconda3\lib\site-packages\scrapyd\webservice.py", line 21, in render
            return JsonResource.render(self, txrequest).encode('utf-8')
          File "e:\anaconda3\lib\site-packages\scrapyd\utils.py", line 20, in render
            r = resource.Resource.render(self, txrequest)
          File "e:\anaconda3\lib\site-packages\twisted\web\resource.py", line 250, in render
            return m(request)
          File "e:\anaconda3\lib\site-packages\scrapyd\webservice.py", line 124, in render_GET
            queue = self.root.poller.queues[project]
        builtins.KeyError: 'ddd'

**Comment by kilakila-heart** [comment]
我用scrapyd-deploy.py -l可以看到对应的项目，但是用spiderkeeper就出现exceptions.KeyError: 'anchor_crawler'？
   Traceback (most recent call last):
          File "c:\programdata\anaconda2\lib\site-packages\twisted\web\http.py", line 2190, in allContentReceived
            req.requestReceived(command, path, version)
          File "c:\programdata\anaconda2\lib\site-packages\twisted\web\http.py", line 917, in requestReceived
            self.process()
          File "c:\programdata\anaconda2\lib\site-packages\twisted\web\server.py", line 198, in process
            self.render(resrc)
          File "c:\programdata\anaconda2\lib\site-packages\twisted\web\server.py", line 258, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "c:\programdata\anaconda2\lib\site-packages\scrapyd\webservice.py", line 21, in render
            return JsonResource.render(self, txrequest).encode('utf-8')
          File "c:\programdata\anaconda2\lib\site-packages\scrapyd\utils.py", line 20, in render
            r = resource.Resource.render(self, txrequest)
          File "c:\programdata\anaconda2\lib\site-packages\twisted\web\resource.py", line 250, in render
            return m(request)
          File "c:\programdata\anaconda2\lib\site-packages\scrapyd\webservice.py", line 124, in render_GET
            queue = self.root.poller.queues[project]
        exceptions.KeyError: 'anchor_crawler'

**Comment by j785786058** [comment]
因为项目里面没有爬虫造成的，因为会定时去查看项目里的爬虫列表，如果项目里没爬虫的话就会说找不到这个项目，于是报错，可以忽略。
