### ISSUE TITLE
No module named loader.processors

### ISSUE THREAD

**Issue by seozed** [DormyMo/SpiderKeeper#35]
````
2017-09-06 02:43:24+0000 [HTTPChannel,223,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1730, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 826, in requestReceived
            self.process()
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 189, in process
            self.render(resrc)
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 238, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/usr/lib/pymodules/python2.7/scrapyd/webservice.py", line 18, in render
            return JsonResource.render(self, txrequest)
          File "/usr/lib/pymodules/python2.7/scrapy/utils/txweb.py", line 10, in render
            r = resource.Resource.render(self, txrequest)
          File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
            return m(request)
          File "/usr/lib/pymodules/python2.7/scrapyd/webservice.py", line 88, in render_GET
            spiders = get_spider_list(project, runner=self.root.runner)
          File "/usr/lib/pymodules/python2.7/scrapyd/utils.py", line 65, in get_spider_list
            raise RuntimeError(msg.splitlines()[-1])
        exceptions.RuntimeError: ImportError: No module named loader.processors

````

这个是什么原因引起的？

scrapyd目前正式版还不支持python3，那如果项目用的是python3写的，会报错不

**Comment by DormyMo** [comment]
只能单独部署了，scrapyd用py2.7部署，当然sk也支持py2.7
